### PR TITLE
Added Naman Sood to past intern section

### PR DESCRIPTION
**Pull request by geekyjunk**

### CODE REVIEW

**Comment by dotangad** [comment]
Why are there changes to about.js?

**Comment by geekyjunk** [comment]
Just removed useless code which was commented earlier by me.

**Comment by dotangad** [comment]
LGTM merging

**Comment by tendstofortytwo** [comment]
Might also want to remove me from the GitHub org/take away my server access rights.

I'm not going to do anything, but it's good practice. ¯\\\_(ツ)_/¯

**Comment by dotangad** [comment]
@namansood only @JAPNIT can remove you from the org, and I think only you have access to the server.

**Comment by tendstofortytwo** [comment]
That's, uh, concerning. @JAPNIT okay if I give access to @dotangad?

**Pull request merged**
